/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExtendedEmployeeProfile {
  'name' : string,
  'isActive' : boolean,
  'loginId' : string,
  'jobTitle' : string,
  'phone' : string,
  'department' : string,
  'linkedPrincipal' : [] | [Principal],
}
export interface Message {
  'content' : string,
  'timestamp' : bigint,
  'senderRole' : MessageRole,
}
export type MessageRole = { 'admin' : null } |
  { 'employee' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreateEmployee' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'employeeLoginWithCredentials' : ActorMethod<
    [string, string],
    ExtendedEmployeeProfile
  >,
  'getAllEmployees' : ActorMethod<[], Array<[bigint, ExtendedEmployeeProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployeeCredentials' : ActorMethod<[bigint], [string, string]>,
  'getMessagesForAdmin' : ActorMethod<[bigint], Array<Message>>,
  'getMessagesForEmployee' : ActorMethod<[], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], undefined>,
  'sendMessageToAdmin' : ActorMethod<[string], undefined>,
  'setEmployeeActiveStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];