/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExtendedEmployeeProfile = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'loginId' : IDL.Text,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'linkedPrincipal' : IDL.Opt(IDL.Principal),
});
export const CallStatus = IDL.Variant({
  'idle' : IDL.Null,
  'calling' : IDL.Null,
  'ended' : IDL.Null,
  'connected' : IDL.Null,
});
export const CallSignal = IDL.Record({
  'status' : CallStatus,
  'offer' : IDL.Opt(IDL.Text),
  'answer' : IDL.Opt(IDL.Text),
  'iceCandidates' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const MessageRole = IDL.Variant({
  'admin' : IDL.Null,
  'employee' : IDL.Null,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderRole' : MessageRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIceCandidateAdmin' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addIceCandidateEmployee' : IDL.Func([IDL.Text], [], []),
  'adminCreateEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'answerVideoCall' : IDL.Func([IDL.Text], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'employeeInitiateVideoCall' : IDL.Func([IDL.Text], [Result], []),
  'employeeLoginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ExtendedEmployeeProfile],
      [],
    ),
  'endCallAdmin' : IDL.Func([IDL.Nat], [], []),
  'endCallEmployee' : IDL.Func([], [], []),
  'getAllEmployees' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ExtendedEmployeeProfile))],
      ['query'],
    ),
  'getCallSignalForAdmin' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CallSignal)],
      ['query'],
    ),
  'getCallSignalForEmployee' : IDL.Func([], [IDL.Opt(CallSignal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployeeCredentials' : IDL.Func(
      [IDL.Nat],
      [IDL.Text, IDL.Text],
      ['query'],
    ),
  'getMessagesForAdmin' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMessagesForEmployee' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateVideoCall' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'sendMessageToAdmin' : IDL.Func([IDL.Text], [], []),
  'setEmployeeActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExtendedEmployeeProfile = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'loginId' : IDL.Text,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'linkedPrincipal' : IDL.Opt(IDL.Principal),
  });
  const CallStatus = IDL.Variant({
    'idle' : IDL.Null,
    'calling' : IDL.Null,
    'ended' : IDL.Null,
    'connected' : IDL.Null,
  });
  const CallSignal = IDL.Record({
    'status' : CallStatus,
    'offer' : IDL.Opt(IDL.Text),
    'answer' : IDL.Opt(IDL.Text),
    'iceCandidates' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const MessageRole = IDL.Variant({
    'admin' : IDL.Null,
    'employee' : IDL.Null,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderRole' : MessageRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIceCandidateAdmin' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addIceCandidateEmployee' : IDL.Func([IDL.Text], [], []),
    'adminCreateEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'answerVideoCall' : IDL.Func([IDL.Text], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'employeeInitiateVideoCall' : IDL.Func([IDL.Text], [Result], []),
    'employeeLoginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ExtendedEmployeeProfile],
        [],
      ),
    'endCallAdmin' : IDL.Func([IDL.Nat], [], []),
    'endCallEmployee' : IDL.Func([], [], []),
    'getAllEmployees' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ExtendedEmployeeProfile))],
        ['query'],
      ),
    'getCallSignalForAdmin' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CallSignal)],
        ['query'],
      ),
    'getCallSignalForEmployee' : IDL.Func([], [IDL.Opt(CallSignal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployeeCredentials' : IDL.Func(
        [IDL.Nat],
        [IDL.Text, IDL.Text],
        ['query'],
      ),
    'getMessagesForAdmin' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMessagesForEmployee' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateVideoCall' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'sendMessageToAdmin' : IDL.Func([IDL.Text], [], []),
    'setEmployeeActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };